# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=20)),
                ('ln', models.CharField(max_length=20)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('CN', 'China'), ('UK', 'United Kingdom'), ('PL', 'Poland')], max_length=8)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('cn', 'Chinese'), ('en', 'English'), ('pl', 'Polish')], max_length=8)),
                ('score', models.FloatField(max_length=2)),
                ('status', models.CharField(choices=[('s1', 'status1'), ('s2', 'status2'), ('s3', 'status3')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('skype', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='./upload/')),
                ('comments', models.TextField(blank=True)),
                ('trained_course', models.ManyToManyField(to='CRlist.Course')),
            ],
        ),
    ]
