# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRlist', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cv',
            field=models.FileField(blank=True, upload_to='./upload/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='score',
            field=models.FloatField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='skype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trained_course',
            field=models.ManyToManyField(blank=True, to='CRlist.Course'),
        ),
    ]
