# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRlist', '0003_auto_20170911_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlist', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.CharField(choices=[('', '----'), ('s1', 'status1'), ('s2', 'status2'), ('s3', 'status3')], max_length=10),
        ),
        migrations.AddField(
            model_name='trainer_list',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRlist.Trainer'),
        ),
    ]
